[build]
  command = "pnpm build"
  publish = "dist"
  functions = ".netlify/functions-internal"

[functions]
  # Include only necessary files
  included_files = [
    "app/**/*.{ts,tsx,js,jsx}",
    "dist/**/*",
    "node_modules/viem/dist/**/*",
    "node_modules/@tanstack/*/dist/**/*",
    "node_modules/@trpc/*/dist/**/*"
  ]
  node_bundler = "esbuild"
  # Increase node version for better ESM support
  node_version = "20"

  [functions.excluded_files]
    files = [
      "**/*.{spec,test}.{ts,tsx,js,jsx}",
      "**/*.map",
      "**/*.md",
      "**/*.d.ts"
    ]
    node_modules = [
      ".pnpm/**",
      ".cache/**",
      ".nitro/**"
    ]
    external_node_modules = [
      "fsevents",
      "@swc/*",
      "@esbuild/*"
    ]

[build.environment]
  NODE_OPTIONS = "--max-old-space-size=4096"
  NITRO_PRESET = "netlify"

[dev]
  framework = "#custom"
  command = "pnpm dev"
  targetPort = 3000
  port = 8888
  publish = "dist" 